@cryptocurrencyId = 3f4918b0-04e6-4f46-a7d6-ad0ffcf3f84a

PUT {{host}}/cryptocurrencies/{{cryptocurrencyId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Solana v2"
}