@portfolioId = ea2a7dfb-f457-4739-8842-37ef2f28c36e

POST {{host}}/portfolio/{{portfolioId}}/transactions
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "cryptocurrencyId": "8611afa1-4621-43e6-a5e4-04c40078f702",
    "amount": 0.3,
    "pricePerToken": 60000
}