@portfolioId = 3bc65634-03b3-4ba9-b56e-97fb3fbb1dd3

POST {{host}}/portfolio/{{portfolioId}}/transactions
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "cryptocurrencyId": "9d31fd5e-d81a-4924-916f-e255f764c597",
    "amount": 2,
    "pricePerToken": 30000,
    "totalPrice": 60000
}