@portfolioId = 7513cf70-1fb2-402f-8012-4b20b1133d38
@transactionId = 183da43c-333a-44ae-84a3-e3e4e03db2c6

GET {{host}}/portfolio/{{portfolioId}}/transactions/{{transactionId}}
Authorization: Bearer {{token}}