@host = http://localhost:5254

GET  {{host}}/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NjI3MTNkZi02ZWJlLTQwNjgtYTQ1Ni1jYzE5N2NhMWNlMTUiLCJnaXZlbl9uYW1lIjoiTGV2IExvZ3Zpbm92IiwianRpIjoiNzQ3NjgzZDItZjU0MC00NzY5LWE3MGEtNTkxY2FhYTljNzhiIiwiZXhwIjoxNzE3Njg5NzE3LCJpc3MiOiJsbG9ndmlub3YiLCJhdWQiOiJsbG9ndmlub3YifQ.iT9ayr69p-RjK9a0DtO1tz_FMoe2tIFaWhBzCzxEzg0