@host = http://localhost:5254

POST {{host}}/portfolio/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTU4NWY0Ni1mNGNjLTQ2YjItYjA5OS0wMmYzZDU1ZDZiOGQiLCJnaXZlbl9uYW1lIjoiTGV2IExvZ3Zpbm92IiwianRpIjoiOTcxYjcxMWUtNzZjNS00MzI1LWE2ZmItODAzZmQ2ZTQ3MzFhIiwiZXhwIjoxNzE4MDMzODYwLCJpc3MiOiJsbG9ndmlub3YiLCJhdWQiOiJsbG9ndmlub3YifQ.YkipjTK4yMCNUYdAxiaASlLlUUgJgtnbvlUz_vmNQ9c
Content-Type: application/json

{
    "title": "Main Wallet"
}